from __future__ import annotations

from typing import Protocol, Any


class SessionStore(Protocol):
    def create_session(self, session_id: str, payload: dict[str, Any]) -> None: ...
    def get_session(self, session_id: str): ...
    def update_session(self, session_id: str, payload: dict[str, Any]) -> None: ...
    def set_result(self, session_id: str, result: Any) -> None: ...
    def get_result(self, session_id: str): ...
    def append_chat_message(self, session_id: str, message: dict[str, Any]) -> None: ...
    def get_chat_history(self, session_id: str): ...
    def create_repo_index(self, index_id: str, payload: dict[str, Any]) -> None: ...
    def get_repo_index(self, index_id: str): ...
    def update_repo_index(self, index_id: str, payload: dict[str, Any]) -> None: ...
    def list_repo_index_history(self, index_id: str): ...
    def save_prd_diff(self, key: str, payload: dict[str, Any]) -> None: ...
    def get_prd_diff(self, key: str): ...
    def save_test_gap_result(self, session_id: str, payload: dict[str, Any]) -> None: ...
    def save_onboarding_report(self, session_id: str, payload: dict[str, Any]) -> None: ...
    def save_pr_analysis_result(self, key: str, payload: dict[str, Any]) -> None: ...
    def cleanup_expired_sessions(self) -> None: ...
