from __future__ import annotations

FORBIDDEN_AS_PRODUCT_IDENTITY = {
    "frontend",
    "backend",
    "app",
    "src",
    "server",
    "client",
    "api",
    "core",
    "project",
    "code",
    "repository",
    "main",
    "service",
}

WEAK_TECHNICAL_SIGNALS = {
    "fastapi",
    "flask",
    "express",
    "mongodb",
    "postgresql",
    "sqlite",
    "/analyze",
    "/query",
    "/summarize",
    "/search",
    "/health",
    "api workflows",
    "background processing",
    "report generation",
    "database integration",
}

EXPLICIT_METADATA_FILES = (
    "readme.md",
    "readme.mdx",
    "package.json",
    "pyproject.toml",
)

DOMAIN_SIGNALS = {
    "repository_intelligence": {
        "repo",
        "repository",
        "codebase",
        "source code",
        "github repository",
        "zip upload",
        "folder upload",
        "project intelligence",
        "code intelligence",
        "developer intelligence",
        "repo chat",
        "prd generation",
        "architecture diff",
        "test gap",
        "onboarding report",
        "mcp tools",
        "analyze repository",
    },
    "ai_hallucination_detection": {
        "hallucination",
        "fact check",
        "fact-check",
        "claim",
        "claim verification",
        "verify",
        "verification",
        "truth",
        "misinformation",
        "web scraping",
        "scraper",
        "crawler",
        "bs4",
        "beautifulsoup",
        "selenium",
        "playwright",
        "requests",
        "source",
        "citation",
        "evidence",
        "url",
        "search result",
        "grounding",
        "grounded answer",
    },
    "healthcare": {
        "diagnose",
        "diagnosis",
        "medical",
        "healthcare",
        "patient",
        "clinical",
        "symptom",
        "knowledge retrieval",
    },
    "ecommerce": {
        "product",
        "cart",
        "checkout",
        "order",
        "payment",
        "inventory",
        "customer",
        "storefront",
    },
    "lms": {
        "course",
        "lesson",
        "student",
        "teacher",
        "quiz",
        "assignment",
        "learning",
    },
    "finance": {
        "invoice",
        "payment",
        "transaction",
        "wallet",
        "ledger",
        "expense",
        "billing",
    },
    "crm": {
        "customer",
        "lead",
        "contact",
        "dashboard",
        "analytics",
        "sales",
        "admin",
    },
    "cms": {
        "post",
        "article",
        "author",
        "editor",
        "comment",
        "category",
        "cms",
        "publish",
    },
    "chatbot": {
        "chat",
        "assistant",
        "conversation",
        "prompt",
        "message",
        "llm",
        "agent",
    },
    "analytics": {
        "analytics",
        "metrics",
        "dashboard",
        "dataset",
        "report",
        "chart",
        "pipeline",
        "insight",
    },
    "devops": {
        "deploy",
        "ci",
        "cd",
        "docker",
        "kubernetes",
        "workflow",
        "job",
        "automation",
        "infra",
    },
}


def is_forbidden_product_identity(name: str) -> bool:
    return str(name or "").strip().lower() in FORBIDDEN_AS_PRODUCT_IDENTITY
