from fpdf import FPDF
from datetime import datetime
from app.docs.models import PRDResult
from app.docs.fact_snapshot import build_fact_snapshot
from app.docs.exporters.diagram_renderer import render_architecture_diagram, render_workflow_diagram
from app.docs.utils.evidence_sanitizer import sanitize_text
from app.docs.utils.production_text import safe_remaining_summary, safe_risk_summary
from app.intelligence.consistency_validator import OutputConsistencyValidator

class AHALPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font("helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, "Generated by AHAL AI - Team Ragnarok", 0, 0, "R")
            self.ln(10)
            self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AHAL AI - Team Ragnarok", 0, 0, "C")
        self.set_text_color(0, 0, 0)

class PDFExporter:
    def __init__(self):
        self.validator = OutputConsistencyValidator()

    def _safe_text(self, value, default=""):
        text = sanitize_text(value, fallback=default)
        text = self._remove_ignored_paths(text)
        return text.encode("latin-1", errors="replace").decode("latin-1")
        
    def _section_content(self, section):
        if section is None:
            return "Insufficient evidence from codebase."
        content = getattr(section, "content", None)
        return self._safe_text(content, "Insufficient evidence from codebase.")

    def _remove_ignored_paths(self, text: str) -> str:
        ignored = ["node_modules", ".venv", "site-packages", "__pycache__", "pip/_vendor", "type='", "confidence='", "reasoning=[", "evidence=[", "EvidenceItem(", "ArchitectureResult("]
        for ig in ignored:
            text = text.replace(ig, "[REDACTED]")
        return text

    def export(self, prd_result: PRDResult, polished_text: dict | None = None, polished_markdown: str | None = None) -> bytes:
        prd_result = self.validator.validate_export_prd(prd_result)
        snapshot = build_fact_snapshot(prd_result=prd_result)
        pdf = AHALPDF()
        export_warnings = self._meaningful_warnings(prd_result)
        polished_text = polished_text if isinstance(polished_text, dict) else None

        # Ensure we don't crash on tests with dummy output
        pdf.set_compression(False)
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        self._render_title_page(pdf, prd_result, snapshot)

        self._section(pdf, "Executive Summary")
        self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "executive_summary", self._section_content(getattr(prd_result, "overview", None))))
        self._paragraph(pdf, f"Project Type: {self._safe_text(getattr(prd_result, 'project_type', 'Unknown'))}.")
        self._paragraph(pdf, f"Architecture Confidence: {self._safe_text(getattr(prd_result, 'architecture_confidence', 'low')).title()}.")
        self._paragraph(pdf, f"Product Purpose Confidence: {self._safe_text(getattr(prd_result, 'product_purpose_confidence', 'low')).title()}.")
        
        self._section(pdf, "Truth Notice")
        self._paragraph(pdf, "This report is generated from static code evidence. Unknowns are reported conservatively.")
        
        # Project Intelligence Brief
        pb = getattr(prd_result, "project_brief", None)
        self._section(pdf, "Project Intelligence Brief")
        self._section(pdf, "Project Goal")
        self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "project_goal", self._brief_section(pb, "goal")))

        self._section(pdf, "What")
        self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "what", self._brief_section(pb, "what", getattr(getattr(prd_result, "overview", None), "content", ""))))

        self._section(pdf, "Why")
        self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "why", self._brief_section(pb, "why")))

        self._section(pdf, "Built Summary")
        self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "built_summary", self._built_summary(prd_result)))
        if pb and pb.completed:
            self._render_two_col_table(pdf, "Completed Item", "Details", [(item.title, item.description) for item in pb.completed])

        if pb and pb.remaining:
            self._section(pdf, "Remaining Summary")
            self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "remaining_summary", self._remaining_summary(prd_result)))
            self._render_two_col_table(pdf, "Remaining Item", "Details", [(item.title, item.description) for item in pb.remaining])
        
        self._section(pdf, "Architecture")
        self._paragraph(pdf, self._section_intro(polished_text, "architecture"))
        self._paragraph(pdf, self._section_content(getattr(prd_result, "architecture", None)))
        render_architecture_diagram(pdf, prd_result)
        
        self._section(pdf, "Technical Stack")
        self._paragraph(pdf, self._section_intro(polished_text, "tech_stack"))
        self._render_tech_stack_table(pdf, snapshot)

        self._section(pdf, "API Surface")
        self._paragraph(pdf, self._section_intro(polished_text, "api_surface"))
        self._render_api_table(pdf, getattr(prd_result, "api_endpoints", []))
        
        self._section(pdf, "Core Modules")
        self._paragraph(pdf, self._section_intro(polished_text, "core_modules"))
        self._render_module_table(pdf, getattr(prd_result, "modules", []))
            
        self._section(pdf, "Workflow")
        self._paragraph(pdf, self._section_intro(polished_text, "workflow"))
        render_workflow_diagram(pdf, prd_result)
        
        self._section(pdf, "Database / Storage")
        self._paragraph(pdf, self._section_intro(polished_text, "database_storage"))
        self._paragraph(pdf, self._section_content(getattr(prd_result, "databases", None)))
        
        self._section(pdf, "Risks and Gaps")
        self._paragraph(pdf, self._narrative_value(prd_result, polished_text, "risk_summary", self._risk_summary(prd_result)))
        risks = self._risk_items(prd_result)
        self._render_risk_table(pdf, risks)
            
        self._section(pdf, "Recommended Next Steps")
        for step in self._next_steps(prd_result, polished_text):
            self._paragraph(pdf, f"- {step}")

        self._section(pdf, "Setup and Run Notes")
        self._paragraph(pdf, self._section_intro(polished_text, "setup_notes"))
        self._paragraph(pdf, self._section_content(getattr(prd_result, "setup_notes", None)))
        
        self._section(pdf, "Evidence Appendix")
        self._paragraph(pdf, self._section_intro(polished_text, "evidence_summary"))
        self._render_evidence_summary(pdf, prd_result)
        
        if export_warnings:
            self._section(pdf, "Warnings Appendix")
            self._paragraph(pdf, self._section_intro(polished_text, "warnings"))
            for w in export_warnings:
                self._paragraph(pdf, f"- {self._safe_text(w)}")
        
        # PDF Exporter doesn't crash on polish failure
        if polished_markdown and not polished_text:
            pdf.add_page()
            self._section(pdf, "Polished LLM Notes")
            self._paragraph(pdf, "The requested PRD was polished by Gemini. However, the exact structural data layout above is retained for maximum deterministic safety.")

        out = pdf.output(dest="S")
        if isinstance(out, bytes):
            return out
        if isinstance(out, bytearray):
            return bytes(out)
        return str(out).encode("latin-1", errors="replace")

    def _section(self, pdf, title: str):
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 10, self._safe_text(title), ln=True)
        pdf.ln(2)
        
    def _paragraph(self, pdf, text: str):
        if not text:
            return
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 5, self._safe_text(text))
        pdf.ln(2)

    def _narrative_value(self, prd_result, polished_text, key: str, fallback: str) -> str:
        if polished_text and isinstance(polished_text.get(key), str):
            return self._safe_text(polished_text[key], fallback)
        return self._safe_text(fallback, "Insufficient evidence from codebase.")

    def _section_intro(self, polished_text, key: str) -> str:
        if polished_text and isinstance(polished_text.get("section_intros"), dict):
            value = polished_text["section_intros"].get(key)
            if isinstance(value, str):
                return self._safe_text(value)
        return ""

    def _brief_section(self, project_brief, key: str, default: str = "Insufficient evidence from codebase.") -> str:
        if not project_brief:
            return default
        section = getattr(project_brief, key, None)
        return getattr(section, "content", default) or default

    def _built_summary(self, prd_result) -> str:
        pb = getattr(prd_result, "project_brief", None)
        if pb and pb.completed:
            rows = [f"{item.title}: {item.description}" for item in pb.completed[:6]]
            return "Built components include: " + "; ".join(rows) + "."
        return "Insufficient evidence from codebase."

    def _remaining_summary(self, prd_result) -> str:
        pb = getattr(prd_result, "project_brief", None)
        if pb and pb.remaining:
            return safe_remaining_summary(pb.remaining)
        return "No significant missing components were detected."

    def _risk_items(self, prd_result):
        pb = getattr(prd_result, "project_brief", None)
        if pb and getattr(pb, "issues", None):
            return pb.issues
        return getattr(prd_result, "risks", [])

    def _risk_summary(self, prd_result) -> str:
        return safe_risk_summary(self._risk_items(prd_result))

    def _next_steps(self, prd_result, polished_text):
        if polished_text and isinstance(polished_text.get("next_steps"), list):
            return [self._safe_text(step) for step in polished_text["next_steps"] if self._safe_text(step)]
        pb = getattr(prd_result, "project_brief", None)
        steps = getattr(pb, "next_steps", []) if pb else []
        if steps:
            return [self._safe_text(step) for step in steps if self._safe_text(step)]
        return ["Proceed with deterministic validation and production-readiness checks."]

    def _render_title_page(self, pdf, prd_result, snapshot):
        pdf.set_fill_color(240, 244, 248)
        pdf.rect(20, 25, 170, 70, style="F")
        pdf.set_font("helvetica", "B", 24)
        pdf.ln(30)
        pdf.cell(0, 10, "AHAL AI", align="C", ln=True)
        pdf.set_font("helvetica", "B", 18)
        pdf.cell(0, 10, "Project Requirement Document", align="C", ln=True)
        pdf.set_font("helvetica", "I", 11)
        pdf.cell(0, 8, "Evidence-backed project intelligence report", align="C", ln=True)
        pdf.ln(12)
        self._render_metadata_card(pdf, prd_result, snapshot)
        pdf.ln(12)
        pdf.set_font("helvetica", "I", 12)
        pdf.cell(0, 10, "Generated by AHAL AI", align="C", ln=True)
        pdf.cell(0, 10, "Team Ragnarok", align="C", ln=True)

    def _render_metadata_card(self, pdf, prd_result, snapshot):
        rows = [
            ("Project Type", self._safe_text(getattr(prd_result, "project_type", "Unknown"))),
            ("Architecture Confidence", self._safe_text(getattr(prd_result, "architecture_confidence", "low")).title()),
            ("Product Purpose Confidence", self._safe_text(getattr(prd_result, "product_purpose_confidence", "low")).title()),
            ("Generated Date", datetime.utcnow().strftime("%Y-%m-%d")),
            ("Evidence Count", str(getattr(prd_result, "evidence_count", 0))),
        ]
        self._render_two_col_table(pdf, "Field", "Value", rows)

    def _render_two_col_table(self, pdf, left_header: str, right_header: str, rows: list[tuple[str, str]]):
        if not rows:
            return
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(55, 8, self._safe_text(left_header), border=1)
        pdf.cell(125, 8, self._safe_text(right_header), border=1, ln=True)
        pdf.set_font("helvetica", "", 9)
        for left, right in rows:
            pdf.cell(55, 8, self._safe_text(left), border=1)
            pdf.cell(125, 8, self._safe_text(right), border=1, ln=True)
        pdf.ln(3)

    def _render_tech_stack_table(self, pdf, snapshot):
        rows = [
            ("Languages", ", ".join(snapshot.language_names) or "No language evidence identified"),
            ("Frameworks", ", ".join(snapshot.framework_names) or "No framework evidence identified"),
            ("Databases / Storage", ", ".join(snapshot.database_names) or "No database/storage layer detected"),
            ("Frontend Frameworks", ", ".join(snapshot.frontend_frameworks) or "None detected"),
            ("Backend Frameworks", ", ".join(snapshot.backend_frameworks) or "None detected"),
        ]
        self._render_two_col_table(pdf, "Category", "Detected Items", rows)

    def _render_module_table(self, pdf, modules):
        if not modules:
            self._paragraph(pdf, "No core modules identified.")
            return
        rows = []
        for mod in modules:
            evidence_text = ", ".join(getattr(mod, "files", []) or []) or "No file evidence listed"
            rows.append((
                self._safe_text(getattr(mod, "name", None)),
                self._safe_text(f"{getattr(mod, 'category', '')} | {getattr(mod, 'description', '')} | {evidence_text}"),
            ))
        self._render_two_col_table(pdf, "Module", "Category | Description | Evidence", rows)

    def _render_api_table(self, pdf, apis):
        if not apis:
            self._paragraph(pdf, "No API endpoints identified.")
            return
        rows = []
        for api in apis:
            rows.append((
                self._safe_text(f"{getattr(api, 'method', '')} {getattr(api, 'path', '')}"),
                self._safe_text(getattr(api, "source_file", None) or getattr(api, "framework", None) or "Unknown source"),
            ))
        self._render_two_col_table(pdf, "Method | Path", "Source", rows)

    def _render_risk_table(self, pdf, risks):
        if risks:
            rows = [
                (
                    self._safe_text(getattr(risk, "severity", None)).title(),
                    self._safe_text(f"{getattr(risk, 'title', '')} | {getattr(risk, 'description', '')} | {getattr(risk, 'recommendation', '')}"),
                )
                for risk in risks
            ]
            self._render_two_col_table(pdf, "Severity", "Issue | Description | Recommendation", rows)
        else:
            self._paragraph(pdf, "No risks identified.")

    def _render_evidence_summary(self, pdf, prd_result):
        evs = []
        
        # Base sections
        db_section = getattr(prd_result, "databases", None)
        setup_section = getattr(prd_result, "setup_notes", None)
        sections = [getattr(prd_result, "overview", None), getattr(prd_result, "architecture", None), getattr(prd_result, "tech_stack", None), db_section, setup_section]
        
        pb = getattr(prd_result, "project_brief", None)
        if pb:
            sections.extend([pb.goal, pb.what, pb.why])
            for item in pb.completed + pb.remaining:
                if hasattr(item, "evidence") and item.evidence:
                    evs.extend(item.evidence)
                    
        for sec in sections:
            if sec and hasattr(sec, "evidence") and sec.evidence:
                evs.extend(sec.evidence)
                
        # List items
        for list_name in ["modules", "api_endpoints", "workflow", "risks"]:
            items = getattr(prd_result, list_name, [])
            for item in items:
                if hasattr(item, "evidence") and item.evidence:
                    evs.extend(item.evidence)
                    
        snapshot = build_fact_snapshot(prd_result=prd_result)
        if not evs:
            self._paragraph(pdf, "No evidence.")
            return
        
        seen = set()
        dedup = []
        framework_rows = 0
        for e in evs:
            reason = self._safe_text(getattr(e, "reason", None), "")
            if not reason:
                continue
            if "detected domain signals for" in reason.lower():
                continue
            if "file extension maps to" in reason.lower():
                continue
            if "configuration evidence" in self._safe_text(getattr(e, "file", None), "").lower() and any(
                self._safe_text(getattr(row, "file", None), "").lower() == "configuration evidence" for row in dedup
            ):
                continue
            if getattr(e, "source_type", "") == "framework":
                framework_rows += 1
                if framework_rows > 3:
                    continue
            if getattr(e, "confidence", "medium") == "low":
                continue
            key = self._safe_text(getattr(e, "file", None)) + reason
            if key not in seen:
                seen.add(key)
                dedup.append(e)
        if snapshot.domain_confidence == "low":
            self._paragraph(pdf, "Product domain could not be determined with high confidence from analyzed evidence.")
        if not dedup:
            self._paragraph(pdf, "Evidence appendix intentionally suppresses low-confidence internal detector noise.")
            return
        for e in dedup[:20]:
            f = self._safe_text(getattr(e, "file", None), "configuration evidence")
            r = self._safe_text(getattr(e, "reason", None), "")
            self._paragraph(pdf, f"- {f}: {r}")
        self._paragraph(pdf, "Additional evidence available in JSON export.")

    def _meaningful_warnings(self, prd_result: PRDResult) -> list[str]:
        warnings = []
        seen = set()
        for item in getattr(prd_result, "warnings", []) or []:
            text = self._safe_text(item, "")
            lowered = text.lower()
            if not text:
                continue
            if "normalized" in lowered and "source" in lowered:
                continue
            if lowered in seen:
                continue
            seen.add(lowered)
            warnings.append(text)
        return warnings
